server:
  port: 8080

spring:
  application:
    # optional
    name: bonz_take-out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bonz
      username: root
      password: root

mybatis-plus:
  configuration:
    # i.e. address_book => addressBook
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # to generate unique primary key
      id-type: assign_id

